apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "clusterbuilders.kpack.io"
spec:
  group: "kpack.io"
  names:
    categories:
      - "kpack"
    kind: "ClusterBuilder"
    listKind: "ClusterBuilderList"
    plural: "clusterbuilders"
    shortNames:
      - "clstbldr"
      - "clstbldrs"
    singular: "clusterbuilder"
  scope: "Cluster"
  versions:
    - additionalPrinterColumns:
        - jsonPath: ".status.latestImage"
          name: "LatestImage"
          type: "string"
        - jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
          name: "Ready"
          type: "string"
      name: "v1alpha1"
      schema:
        openAPIV3Schema:
          type: "object"
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
