apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "bitwarden-secrets.lerentis.uploadfilter24.eu"
spec:
  group: "lerentis.uploadfilter24.eu"
  names:
    kind: "BitwardenSecret"
    plural: "bitwarden-secrets"
    shortNames:
      - "bws"
    singular: "bitwarden-secret"
  scope: "Namespaced"
  versions:
    - name: "v1beta8"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                annotations:
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
                content:
                  items:
                    properties:
                      element:
                        properties:
                          secretName:
                            type: "string"
                          secretRef:
                            type: "string"
                          secretScope:
                            type: "string"
                        required:
                          - "secretName"
                        type: "object"
                    type: "object"
                  type: "array"
                id:
                  type: "string"
                labels:
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
                name:
                  type: "string"
                namespace:
                  type: "string"
                secretType:
                  type: "string"
              required:
                - "id"
                - "namespace"
                - "name"
              type: "object"
          type: "object"
      served: true
      storage: true
