apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "bitwarden-templates.lerentis.uploadfilter24.eu"
spec:
  group: "lerentis.uploadfilter24.eu"
  names:
    kind: "BitwardenTemplate"
    plural: "bitwarden-templates"
    shortNames:
      - "bwt"
    singular: "bitwarden-template"
  scope: "Namespaced"
  versions:
    - name: "v1beta6"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                annotations:
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
                filename:
                  type: "string"
                labels:
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
                name:
                  type: "string"
                namespace:
                  type: "string"
                template:
                  type: "string"
              required:
                - "filename"
                - "template"
                - "namespace"
                - "name"
              type: "object"
          type: "object"
      served: true
      storage: true
