apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "apisixclusterconfigs.apisix.apache.org"
spec:
  group: "apisix.apache.org"
  names:
    kind: "ApisixClusterConfig"
    plural: "apisixclusterconfigs"
    shortNames:
      - "acc"
    singular: "apisixclusterconfig"
  preserveUnknownFields: false
  scope: "Cluster"
  versions:
    - name: "v2"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                admin:
                  properties:
                    adminKey:
                      type: "string"
                    baseURL:
                      pattern: "https?://[^:]+:(\\d+)"
                      type: "string"
                  required:
                    - "baseURL"
                  type: "object"
                ingressClassName:
                  type: "string"
                monitoring:
                  properties:
                    prometheus:
                      properties:
                        enable:
                          type: "boolean"
                        prefer_name:
                          type: "boolean"
                      type: "object"
                    skywalking:
                      properties:
                        enable:
                          type: "boolean"
                        sampleRatio:
                          maximum: 1.0
                          minimum: 0.00001
                          type: "number"
                      type: "object"
                  type: "object"
              type: "object"
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        type: "string"
                      message:
                        type: "string"
                      reason:
                        type: "string"
                      status:
                        type: "string"
                      type:
                        type: "string"
                    type: "object"
                  required:
                    - "type"
                    - "status"
                    - "lastTransitionTime"
                  type: "array"
                observedGeneration:
                  type: "integer"
              type: "object"
          type: "object"
      served: true
      storage: true
      subresources:
        status: {}
