apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "works.multicluster.x-k8s.io"
spec:
  group: "multicluster.x-k8s.io"
  names:
    kind: "Work"
    plural: "works"
    singular: "work"
  scope: "Namespaced"
  versions:
    - name: "v1alpha1"
      schema:
        openAPIV3Schema:
          description: "Work is the Schema for the works API"
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: "string"
            kind:
              description: "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: "string"
            metadata:
              type: "object"
            spec:
              description: "spec defines the workload of a work."
              properties:
                workload:
                  description: "Workload represents the manifest workload to be deployed on spoke cluster"
                  properties:
                    manifests:
                      description: "Manifests represents a list of kuberenetes resources to be deployed on the spoke cluster."
                      items:
                        description: "Manifest represents a resource to be deployed on spoke cluster"
                        type: "object"
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true
                      type: "array"
                  type: "object"
              type: "object"
            status:
              description: "status defines the status of each applied manifest on the spoke cluster."
              properties:
                conditions:
                  description: "Conditions contains the different condition statuses for this work.\nValid condition types are:\n1. Applied represents workload in Work is applied successfully on the spoke cluster.\n2. Progressing represents workload in Work in the trasitioning from one state to another the on the spoke cluster.\n3. Available represents workload in Work exists on the spoke cluster.\n4. Degraded represents the current state of workload does not match the desired\nstate for a certain period."
                  items:
                    description: "Condition contains details for one aspect of the current state of this API Resource."
                    properties:
                      lastTransitionTime:
                        description: "lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
                        format: "date-time"
                        type: "string"
                      message:
                        description: "message is a human readable message indicating details about the transition.\nThis may be an empty string."
                        maxLength: 32768
                        type: "string"
                      observedGeneration:
                        description: "observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
                        format: "int64"
                        minimum: 0.0
                        type: "integer"
                      reason:
                        description: "reason contains a programmatic identifier indicating the reason for the condition's last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty."
                        maxLength: 1024
                        minLength: 1
                        pattern: "^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$"
                        type: "string"
                      status:
                        description: "status of the condition, one of True, False, Unknown."
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                        type: "string"
                      type:
                        description: "type of condition in CamelCase or in foo.example.com/CamelCase."
                        maxLength: 316
                        pattern: "^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$"
                        type: "string"
                    required:
                      - "lastTransitionTime"
                      - "message"
                      - "reason"
                      - "status"
                      - "type"
                    type: "object"
                  type: "array"
                manifestConditions:
                  description: "ManifestConditions represents the conditions of each resource in work deployed on\nspoke cluster."
                  items:
                    description: "ManifestCondition represents the conditions of the resources deployed on\nspoke cluster"
                    properties:
                      conditions:
                        description: "Conditions represents the conditions of this resource on spoke cluster"
                        items:
                          description: "Condition contains details for one aspect of the current state of this API Resource."
                          properties:
                            lastTransitionTime:
                              description: "lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
                              format: "date-time"
                              type: "string"
                            message:
                              description: "message is a human readable message indicating details about the transition.\nThis may be an empty string."
                              maxLength: 32768
                              type: "string"
                            observedGeneration:
                              description: "observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
                              format: "int64"
                              minimum: 0.0
                              type: "integer"
                            reason:
                              description: "reason contains a programmatic identifier indicating the reason for the condition's last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty."
                              maxLength: 1024
                              minLength: 1
                              pattern: "^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$"
                              type: "string"
                            status:
                              description: "status of the condition, one of True, False, Unknown."
                              enum:
                                - "True"
                                - "False"
                                - "Unknown"
                              type: "string"
                            type:
                              description: "type of condition in CamelCase or in foo.example.com/CamelCase."
                              maxLength: 316
                              pattern: "^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$"
                              type: "string"
                          required:
                            - "lastTransitionTime"
                            - "message"
                            - "reason"
                            - "status"
                            - "type"
                          type: "object"
                        type: "array"
                      identifier:
                        description: "resourceId represents a identity of a resource linking to manifests in spec."
                        properties:
                          group:
                            description: "Group is the group of the resource."
                            type: "string"
                          kind:
                            description: "Kind is the kind of the resource."
                            type: "string"
                          name:
                            description: "Name is the name of the resource"
                            type: "string"
                          namespace:
                            description: "Namespace is the namespace of the resource, the resource is cluster scoped if the value\nis empty"
                            type: "string"
                          ordinal:
                            description: "Ordinal represents an index in manifests list, so the condition can still be linked\nto a manifest even thougth manifest cannot be parsed successfully."
                            type: "integer"
                          resource:
                            description: "Resource is the resource type of the resource"
                            type: "string"
                          version:
                            description: "Version is the version of the resource."
                            type: "string"
                        required:
                          - "ordinal"
                        type: "object"
                    required:
                      - "conditions"
                      - "identifier"
                    type: "object"
                  type: "array"
              required:
                - "conditions"
              type: "object"
          type: "object"
      served: true
      storage: true
      subresources:
        status: {}
