apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    app.kubernetes.io/name: "akv2k8s"
  name: "azurekeyvaultidentities.spv.no"
spec:
  group: "spv.no"
  names:
    categories:
      - "all"
    kind: "AzureKeyVaultIdentity"
    listKind: "AzureKeyVaultIdentityList"
    plural: "azurekeyvaultidentities"
    shortNames:
      - "akvi"
    singular: "azurekeyvaultidentity"
  scope: "Namespaced"
  versions:
    - name: "v1alpha1"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                name:
                  description: "Name of the Azure Managed Identity to"
                  type: "string"
              required:
                - "identity"
      served: true
      storage: true
