apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "hawkbits.iot.eclipse.org"
spec:
  group: "iot.eclipse.org"
  names:
    kind: "Hawkbit"
    plural: "hawkbits"
    singular: "hawkbit"
  scope: "Namespaced"
  versions:
    - additionalPrinterColumns:
        - description: "The current phase of the deployment"
          jsonPath: ".status.phase"
          name: "Phase"
          type: "string"
        - description: "Status message"
          jsonPath: ".status.message"
          name: "Message"
          type: "string"
      name: "v1alpha1"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                database:
                  oneOf:
                    - required:
                        - "mysql"
                    - required:
                        - "postgres"
                    - required:
                        - "embedded"
                  properties:
                    embedded:
                      type: "object"
                    mysql:
                      oneOf:
                        - required:
                            - "url"
                        - required:
                            - "host"
                            - "database"
                      properties:
                        database:
                          type: "string"
                        host:
                          type: "string"
                        passwordSecret:
                          properties:
                            field:
                              type: "string"
                            name:
                              type: "string"
                          type: "object"
                        port:
                          type: "integer"
                        url:
                          type: "string"
                        username:
                          type: "string"
                      type: "object"
                    postgres:
                      oneOf:
                        - required:
                            - "url"
                        - required:
                            - "host"
                            - "database"
                      properties:
                        database:
                          type: "string"
                        host:
                          type: "string"
                        passwordSecret:
                          properties:
                            field:
                              type: "string"
                            name:
                              type: "string"
                          type: "object"
                        port:
                          type: "integer"
                        url:
                          type: "string"
                        username:
                          type: "string"
                      type: "object"
                  type: "object"
                imageOverrides:
                  additionalProperties:
                    properties:
                      image:
                        type: "string"
                      pullPolicy:
                        type: "string"
                    type: "object"
                  type: "object"
                rabbit:
                  oneOf:
                    - required:
                        - "external"
                    - required:
                        - "managed"
                  properties:
                    external:
                      properties:
                        host:
                          type: "string"
                        passwordSecret:
                          properties:
                            field:
                              type: "string"
                            name:
                              type: "string"
                          type: "object"
                        port:
                          type: "integer"
                        username:
                          type: "string"
                      required:
                        - "host"
                      type: "object"
                    managed:
                      properties:
                        resources:
                          type: "object"
                        storageSize:
                          type: "string"
                      type: "object"
                  type: "object"
                signOn:
                  properties:
                    keycloak:
                      properties:
                        hawkbitUrl:
                          type: "string"
                        instanceSelector:
                          description: "Selector for looking up Keycloak Custom Resources."
                          properties:
                            matchExpressions:
                              description: "matchExpressions is a list of label selector requirements. The requirements are ANDed."
                              items:
                                description: "A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values."
                                properties:
                                  key:
                                    description: "key is the label key that the selector applies to."
                                    type: "string"
                                  operator:
                                    description: "operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist."
                                    type: "string"
                                  values:
                                    description: "values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."
                                    items:
                                      type: "string"
                                    type: "array"
                                required:
                                  - "key"
                                  - "operator"
                                type: "object"
                              type: "array"
                            matchLabels:
                              additionalProperties:
                                type: "string"
                              description: "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed."
                              type: "object"
                          type: "object"
                      type: "object"
                  type: "object"
              type: "object"
            status:
              properties:
                message:
                  type: "string"
                phase:
                  type: "string"
              type: "object"
          type: "object"
      served: true
      storage: true
      subresources:
        status: {}
