apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: metrictemplates.flagger.app
spec:
  group: flagger.app
  names:
    categories:
    - all
    kind: MetricTemplate
    listKind: MetricTemplateList
    plural: metrictemplates
    singular: metrictemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.provider.type
      name: Provider
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: MetricTemplate is the Schema for the MetricTemplates API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MetricTemplateSpec defines the desired state of a MetricTemplate.
            properties:
              provider:
                description: Provider of this metric template
                properties:
                  address:
                    description: API address of this provider
                    type: string
                  insecureSkipVerify:
                    description: Disable SSL certificate validation for the provider address
                    type: boolean
                  region:
                    description: Region of the provider
                    type: string
                  secretRef:
                    description: Kubernetes secret reference containing the provider credentials
                    properties:
                      name:
                        description: Name of the Kubernetes secret
                        type: string
                    required:
                    - name
                    type: object
                  type:
                    description: Type of this provider
                    enum:
                    - prometheus
                    - influxdb
                    - datadog
                    - stackdriver
                    - cloudwatch
                    - newrelic
                    - graphite
                    - dynatrace
                    type: string
                required:
                - type
                type: object
              query:
                description: Query of this metric template
                type: string
            required:
            - provider
            - query
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
