apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "clusters.ensembleoss.io"
spec:
  group: "ensembleoss.io"
  names:
    kind: "Cluster"
    plural: "clusters"
    singular: "cluster"
  scope: "Namespaced"
  versions:
    - name: "v1"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                backend:
                  properties:
                    name:
                      type: "string"
                  required:
                    - "name"
                  type: "object"
                depends:
                  items:
                    type: "string"
                  type: "array"
                groups:
                  items:
                    properties:
                      name:
                        type: "string"
                      params:
                        additionalProperties:
                          type: "string"
                        type: "object"
                      replicas:
                        type: "integer"
                      type:
                        type: "string"
                    required:
                      - "replicas"
                    type: "object"
                  type: "array"
              required:
                - "backend"
              type: "object"
            status:
              properties:
                observedGeneration:
                  type: "integer"
              type: "object"
          type: "object"
      served: true
      storage: true
      subresources:
        status: {}
