apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "resources.ensembleoss.io"
spec:
  group: "ensembleoss.io"
  names:
    kind: "Resource"
    plural: "resources"
    singular: "resource"
  scope: "Namespaced"
  versions:
    - name: "v1"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                cluster:
                  type: "string"
                params:
                  additionalProperties:
                    type: "string"
                  type: "object"
                resource:
                  type: "string"
              required:
                - "cluster"
                - "resource"
              type: "object"
            status:
              properties:
                observedGeneration:
                  type: "integer"
              type: "object"
          type: "object"
      served: true
      storage: true
      subresources:
        status: {}
