// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium --docs --derive=Default --derive=PartialEq --smart-derive-elision --filename crd-catalog/opensearch-project/opensearch-k8s-operator/opensearch.opster.io/v1/opensearchindextemplates.yaml
// kopium version: 0.21.2

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Serialize, Deserialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[kube(group = "opensearch.opster.io", version = "v1", kind = "OpensearchIndexTemplate", plural = "opensearchindextemplates")]
#[kube(namespaced)]
#[kube(status = "OpensearchIndexTemplateStatus")]
#[kube(schema = "disabled")]
#[kube(derive="Default")]
#[kube(derive="PartialEq")]
pub struct OpensearchIndexTemplateSpec {
    /// Optional user metadata about the index template
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "_meta")]
    pub meta: Option<serde_json::Value>,
    /// An ordered list of component template names. Component templates are merged in the order specified,
    /// meaning that the last component template specified has the highest precedence
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "composedOf")]
    pub composed_of: Option<Vec<String>>,
    /// The dataStream config that should be applied
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "dataStream")]
    pub data_stream: Option<OpensearchIndexTemplateDataStream>,
    /// Array of wildcard expressions used to match the names of indices during creation
    #[serde(rename = "indexPatterns")]
    pub index_patterns: Vec<String>,
    /// The name of the index template. Defaults to metadata.name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// LocalObjectReference contains enough information to let you locate the
    /// referenced object inside the same namespace.
    #[serde(rename = "opensearchCluster")]
    pub opensearch_cluster: OpensearchIndexTemplateOpensearchCluster,
    /// Priority to determine index template precedence when a new data stream or index is created.
    /// The index template with the highest priority is chosen
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<i64>,
    /// The template that should be applied
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template: Option<OpensearchIndexTemplateTemplate>,
    /// Version number used to manage the component template externally
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

/// The dataStream config that should be applied
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct OpensearchIndexTemplateDataStream {
    /// TimestampField for dataStream
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp_field: Option<OpensearchIndexTemplateDataStreamTimestampField>,
}

/// TimestampField for dataStream
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct OpensearchIndexTemplateDataStreamTimestampField {
    /// Name of the field that are used for the DataStream
    pub name: String,
}

/// LocalObjectReference contains enough information to let you locate the
/// referenced object inside the same namespace.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct OpensearchIndexTemplateOpensearchCluster {
    /// Name of the referent.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    /// TODO: Add other useful fields. apiVersion, kind, uid?
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// The template that should be applied
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct OpensearchIndexTemplateTemplate {
    /// Aliases to add
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aliases: Option<BTreeMap<String, OpensearchIndexTemplateTemplateAliases>>,
    /// Mapping for fields in the index
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mappings: Option<serde_json::Value>,
    /// Configuration options for the index
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
}

/// Aliases to add
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct OpensearchIndexTemplateTemplateAliases {
    /// The name of the alias.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    /// Query used to limit documents the alias can access.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// The name of the index that the alias points to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub index: Option<String>,
    /// If true, the index is the write index for the alias
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "isWriteIndex")]
    pub is_write_index: Option<bool>,
    /// Value used to route indexing and search operations to a specific shard.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub routing: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct OpensearchIndexTemplateStatus {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "existingIndexTemplate")]
    pub existing_index_template: Option<bool>,
    /// Name of the currently managed index template
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "indexTemplateName")]
    pub index_template_name: Option<String>,
    /// UID is a type that holds unique ID values, including UUIDs.  Because we
    /// don't ONLY use UUIDs, this is an alias to string.  Being a type captures
    /// intent and helps make sure that UIDs and names do not get conflated.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "managedCluster")]
    pub managed_cluster: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

