apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  labels:
    app.kubernetes.io/part-of: "netcheck"
  name: "networkassertions.netchecks.io"
spec:
  group: "netchecks.io"
  names:
    kind: "NetworkAssertion"
    listKind: "NetworkAssertionList"
    plural: "networkassertions"
    shortNames:
      - "nas"
    singular: "networkassertion"
  scope: "Namespaced"
  versions:
    - additionalPrinterColumns:
        - jsonPath: ".spec.schedule"
          name: "Schedule"
          type: "string"
      name: "v1"
      schema:
        openAPIV3Schema:
          description: "NetworkAssertion is the Schema for the networkassertions API"
          properties:
            spec:
              type: "object"
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: "object"
              x-kubernetes-preserve-unknown-fields: true
          type: "object"
      served: true
      storage: true
