// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium --docs --derive=Default --derive=PartialEq --smart-derive-elision --filename crd-catalog/netbirdio/kubernetes-operator/netbird.io/v1alpha1/groups.yaml
// kopium version: 0.23.0

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Serialize, Deserialize};
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
}

use self::prelude::*;

/// GroupSpec defines the desired state of Group.
#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[kube(group = "netbird.io", version = "v1alpha1", kind = "Group", plural = "groups")]
#[kube(namespaced)]
#[kube(status = "GroupStatus")]
#[kube(schema = "disabled")]
#[kube(derive="Default")]
#[kube(derive="PartialEq")]
pub struct GroupSpec {
    /// Name of the group.
    pub name: String,
}

/// GroupStatus defines the observed state of Group.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct GroupStatus {
    /// Conditions holds the conditions for the Group.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    /// GroupID is the id of the created group.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "groupID")]
    pub group_id: Option<String>,
    /// ObservedGeneration is the last reconciled generation.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "observedGeneration")]
    pub observed_generation: Option<i64>,
}

