apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "bbbfrontends.b3scale.infra.run"
spec:
  group: "b3scale.infra.run"
  names:
    kind: "BBBFrontend"
    listKind: "BBBFrontendList"
    plural: "bbbfrontends"
    singular: "bbbfrontend"
  scope: "Namespaced"
  versions:
    - name: "v1"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "Desired state of the BBBFrontend resource."
              properties:
                credentials:
                  description: "Predefined credentials for the B3scale instance"
                  nullable: true
                  properties:
                    key:
                      description: "Predefined key for B3scale instance, will be defined if not set"
                      type: "string"
                    secretRef:
                      description: "SecretRef is a reference to a key in a Secret resource containing the key to connect to the BBB instance."
                      properties:
                        key:
                          description: "The key of the entry in the Secret resource's `data` field to be used."
                          type: "string"
                        name:
                          description: "Name of the resource being referred to. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                          type: "string"
                      required:
                        - "name"
                        - "key"
                      type: "object"
                  type: "object"
                settings:
                  description: "Settings defines the B3Scale instance settings"
                  properties:
                    create_default_params:
                      additionalProperties:
                        type: "string"
                      description: "See https://github.com/b3scale/b3scale#configure-create-parameter-defaults-and-overrides"
                      nullable: true
                      type: "object"
                    create_override_params:
                      additionalProperties:
                        type: "string"
                      description: "See https://github.com/b3scale/b3scale#configure-create-parameter-defaults-and-overrides"
                      nullable: true
                      type: "object"
                    default_presentation:
                      description: "See https://github.com/b3scale/b3scale#middleware-configuration"
                      nullable: true
                      properties:
                        force:
                          type: "boolean"
                        url:
                          type: "string"
                      type: "object"
                    required_tags:
                      description: "See https://github.com/b3scale/b3scale#middleware-configuration"
                      items:
                        type: "string"
                      nullable: true
                      type: "array"
                  type: "object"
              type: "object"
            status:
              description: "Status of the BBBFrontend. This is set and managed automatically."
              properties:
                conditions:
                  description: "List of status conditions to indicate the status of the BBB frontend. Known condition types are `Ready`."
                  items:
                    description: "BBBFrontendCondition contains condition information for an BBBFrontend."
                    properties:
                      lastTransitionTime:
                        description: "LastTransitionTime is the timestamp corresponding to the last status change of this condition."
                        format: "date-time"
                        type: "string"
                      message:
                        description: "Message is a human readable description of the details of the last transition, complementing reason."
                        type: "string"
                      observedGeneration:
                        description: "If set, this represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.condition[x].observedGeneration is 9, the condition is out of date with respect to the current state of the BBBFrontend."
                        format: "int64"
                        type: "integer"
                      reason:
                        description: "Reason is a brief machine readable explanation for the condition's last transition."
                        type: "string"
                      status:
                        description: "Status of the condition, one of (`True`, `False`, `Unknown`)."
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                        type: "string"
                      type:
                        description: "Type of the condition, known values are (`Ready`)."
                        type: "string"
                    required:
                      - "status"
                      - "type"
                    type: "object"
                  type: "array"
              type: "object"
          type: "object"
      served: true
      storage: true
      subresources:
        status: {}
