apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "buildpacks.kpack.io"
spec:
  group: "kpack.io"
  names:
    categories:
      - "kpack"
    kind: "Buildpack"
    listKind: "BuildpackList"
    plural: "buildpacks"
    shortNames:
      - "bp"
      - "bps"
    singular: "buildpack"
  scope: "Namespaced"
  versions:
    - additionalPrinterColumns:
        - jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
          name: "Ready"
          type: "string"
      name: "v1alpha2"
      schema:
        openAPIV3Schema:
          type: "object"
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
