apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "images.kpack.io"
spec:
  conversion:
    strategy: "Webhook"
    webhook:
      clientConfig:
        service:
          name: "kpack-webhook"
          namespace: "kpack"
          path: "/convert"
          port: 443
      conversionReviewVersions:
        - "v1"
  group: "kpack.io"
  names:
    categories:
      - "kpack"
    kind: "Image"
    listKind: "ImageList"
    plural: "images"
    shortNames:
      - "cnbimage"
      - "cnbimages"
      - "img"
      - "imgs"
    singular: "image"
  scope: "Namespaced"
  versions:
    - additionalPrinterColumns:
        - jsonPath: ".status.latestImage"
          name: "LatestImage"
          type: "string"
        - jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
          name: "Ready"
          type: "string"
      name: "v1alpha2"
      schema:
        openAPIV3Schema:
          type: "object"
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
