apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "oauth2clients.dex.coreos.com"
spec:
  group: "dex.coreos.com"
  names:
    kind: "OAuth2Client"
    listKind: "OAuth2ClientList"
    plural: "oauth2clients"
    singular: "oauth2client"
  scope: "Namespaced"
  versions:
    - name: "v1"
      schema:
        openAPIV3Schema:
          type: "object"
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
