apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "offlinesessionses.dex.coreos.com"
spec:
  group: "dex.coreos.com"
  names:
    kind: "OfflineSessions"
    listKind: "OfflineSessionsList"
    plural: "offlinesessionses"
    singular: "offlinesessions"
  scope: "Namespaced"
  versions:
    - name: "v1"
      schema:
        openAPIV3Schema:
          type: "object"
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
