apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: signingkeies.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: SigningKey
    listKind: SigningKeyList
    plural: signingkeies
    singular: signingkey
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
