apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes-sigs/boskos/pull/105"
  name: "resources.boskos.k8s.io"
spec:
  group: "boskos.k8s.io"
  names:
    kind: "ResourceObject"
    listKind: "ResourceObjectList"
    plural: "resources"
    singular: "resource"
  scope: "Namespaced"
  versions:
    - additionalPrinterColumns:
        - description: "The resource type."
          jsonPath: ".spec.type"
          name: "Type"
          type: "string"
        - description: "The current state of the resource."
          jsonPath: ".status.state"
          name: "State"
          type: "string"
        - description: "The current owner of the resource."
          jsonPath: ".status.owner"
          name: "Owner"
          type: "string"
        - jsonPath: ".status.lastUpdate"
          name: "Last-Updated"
          type: "date"
      name: "v1"
      schema:
        openAPIV3Schema:
          description: "Abstracts any resource type that can be tracked by boskos"
          properties:
            spec:
              description: "Holds information that are not likely to change"
              properties:
                type:
                  type: "string"
              type: "object"
            status:
              description: "Holds information that are likely to change"
              properties:
                expirationDate:
                  format: "date-time"
                  type: "string"
                lastUpdate:
                  format: "date-time"
                  type: "string"
                owner:
                  type: "string"
                state:
                  type: "string"
                userData:
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
              type: "object"
          type: "object"
      served: true
      storage: true
