pub mod vmalertmanagerconfigs;
pub mod vmnodescrapes;
pub mod vmpodscrapes;
pub mod vmprobes;
pub mod vmrules;
pub mod vmscrapeconfigs;
pub mod vmservicescrapes;
pub mod vmstaticscrapes;
pub mod vmusers;
