// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium --docs --filename=./crd-catalog/clusternet/clusternet/apps.clusternet.io/v1alpha1/manifests.yaml --derive=Default --derive=PartialEq
// kopium version: 0.17.2





