apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "configurations.akri.sh"
spec:
  group: "akri.sh"
  names:
    kind: "Configuration"
    plural: "configurations"
    shortNames:
      - "akric"
    singular: "configuration"
  scope: "Namespaced"
  versions:
    - additionalPrinterColumns:
        - description: "The capacity for each Instance discovered"
          jsonPath: ".spec.capacity"
          name: "Capacity"
          type: "string"
        - jsonPath: ".metadata.creationTimestamp"
          name: "Age"
          type: "date"
      name: "v0"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                brokerProperties:
                  additionalProperties:
                    type: "string"
                  type: "object"
                brokerSpec:
                  properties:
                    brokerJobSpec:
                      nullable: true
                      type: "object"
                      x-kubernetes-preserve-unknown-fields: true
                    brokerPodSpec:
                      nullable: true
                      type: "object"
                      x-kubernetes-preserve-unknown-fields: true
                  type: "object"
                capacity:
                  type: "integer"
                configurationServiceSpec:
                  nullable: true
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
                discoveryHandler:
                  properties:
                    discoveryDetails:
                      type: "string"
                    discoveryProperties:
                      items:
                        oneOf:
                          - required:
                              - "value"
                          - required:
                              - "valueFrom"
                        properties:
                          name:
                            pattern: "^[_A-Za-z][_A-Za-z0-9]*$"
                            type: "string"
                          value:
                            nullable: true
                            type: "string"
                          valueFrom:
                            oneOf:
                              - required:
                                  - "secretKeyRef"
                              - required:
                                  - "configMapKeyRef"
                            properties:
                              configMapKeyRef:
                                properties:
                                  key:
                                    type: "string"
                                  name:
                                    type: "string"
                                  namespace:
                                    type: "string"
                                  optional:
                                    type: "boolean"
                                required:
                                  - "name"
                                type: "object"
                              secretKeyRef:
                                properties:
                                  key:
                                    type: "string"
                                  name:
                                    type: "string"
                                  namespace:
                                    type: "string"
                                  optional:
                                    type: "boolean"
                                required:
                                  - "name"
                                type: "object"
                            type: "object"
                        required:
                          - "name"
                        type: "object"
                      nullable: true
                      type: "array"
                    name:
                      type: "string"
                  type: "object"
                instanceServiceSpec:
                  nullable: true
                  type: "object"
                  x-kubernetes-preserve-unknown-fields: true
              type: "object"
          type: "object"
      served: true
      storage: true
