#[cfg(feature = "about_k8s_io_v1alpha1")]
pub mod about_k8s_io_v1alpha1;
#[cfg(feature = "acme_cert_manager_io_v1")]
pub mod acme_cert_manager_io_v1;
#[cfg(feature = "addons_cluster_x_k8s_io_v1alpha4")]
pub mod addons_cluster_x_k8s_io_v1alpha4;
#[cfg(feature = "addons_cluster_x_k8s_io_v1beta1")]
pub mod addons_cluster_x_k8s_io_v1beta1;
#[cfg(feature = "agent_k8s_elastic_co_v1alpha1")]
pub mod agent_k8s_elastic_co_v1alpha1;
#[cfg(feature = "apicodegen_apimatic_io_v1beta1")]
pub mod apicodegen_apimatic_io_v1beta1;
#[cfg(feature = "apiextensions_crossplane_io_v1")]
pub mod apiextensions_crossplane_io_v1;
#[cfg(feature = "apigatewayv2_services_k8s_aws_v1alpha1")]
pub mod apigatewayv2_services_k8s_aws_v1alpha1;
#[cfg(feature = "apm_k8s_elastic_co_v1")]
pub mod apm_k8s_elastic_co_v1;
#[cfg(feature = "apm_k8s_elastic_co_v1beta1")]
pub mod apm_k8s_elastic_co_v1beta1;
#[cfg(feature = "app_kiegroup_org_v1beta1")]
pub mod app_kiegroup_org_v1beta1;
#[cfg(feature = "app_lightbend_com_v1alpha1")]
pub mod app_lightbend_com_v1alpha1;
#[cfg(feature = "app_redislabs_com_v1")]
pub mod app_redislabs_com_v1;
#[cfg(feature = "app_redislabs_com_v1alpha1")]
pub mod app_redislabs_com_v1alpha1;
#[cfg(feature = "applicationautoscaling_services_k8s_aws_v1alpha1")]
pub mod applicationautoscaling_services_k8s_aws_v1alpha1;
#[cfg(feature = "appprotect_f5_com_v1beta1")]
pub mod appprotect_f5_com_v1beta1;
#[cfg(feature = "appprotectdos_f5_com_v1beta1")]
pub mod appprotectdos_f5_com_v1beta1;
#[cfg(feature = "apps_3scale_net_v1alpha1")]
pub mod apps_3scale_net_v1alpha1;
#[cfg(feature = "apps_clusternet_io_v1alpha1")]
pub mod apps_clusternet_io_v1alpha1;
#[cfg(feature = "apps_gitlab_com_v1beta1")]
pub mod apps_gitlab_com_v1beta1;
#[cfg(feature = "apps_kubedl_io_v1alpha1")]
pub mod apps_kubedl_io_v1alpha1;
#[cfg(feature = "apps_kubeedge_io_v1alpha1")]
pub mod apps_kubeedge_io_v1alpha1;
#[cfg(feature = "apps_m88i_io_v1alpha1")]
pub mod apps_m88i_io_v1alpha1;
#[cfg(feature = "aquasecurity_github_io_v1alpha1")]
pub mod aquasecurity_github_io_v1alpha1;
#[cfg(feature = "argoproj_io_v1alpha1")]
pub mod argoproj_io_v1alpha1;
#[cfg(feature = "argoproj_io_v1beta1")]
pub mod argoproj_io_v1beta1;
#[cfg(feature = "asdb_aerospike_com_v1")]
pub mod asdb_aerospike_com_v1;
#[cfg(feature = "asdb_aerospike_com_v1beta1")]
pub mod asdb_aerospike_com_v1beta1;
#[cfg(feature = "atlasmap_io_v1alpha1")]
pub mod atlasmap_io_v1alpha1;
#[cfg(feature = "autoscaling_k8s_io_v1")]
pub mod autoscaling_k8s_io_v1;
#[cfg(feature = "autoscaling_k8s_io_v1beta2")]
pub mod autoscaling_k8s_io_v1beta2;
#[cfg(feature = "autoscaling_karmada_io_v1alpha1")]
pub mod autoscaling_karmada_io_v1alpha1;
#[cfg(feature = "azure_microsoft_com_v1alpha1")]
pub mod azure_microsoft_com_v1alpha1;
#[cfg(feature = "azure_microsoft_com_v1alpha2")]
pub mod azure_microsoft_com_v1alpha2;
#[cfg(feature = "azure_microsoft_com_v1beta1")]
pub mod azure_microsoft_com_v1beta1;
#[cfg(feature = "b3scale_infra_run_v1")]
pub mod b3scale_infra_run_v1;
#[cfg(feature = "batch_volcano_sh_v1alpha1")]
pub mod batch_volcano_sh_v1alpha1;
#[cfg(feature = "beat_k8s_elastic_co_v1beta1")]
pub mod beat_k8s_elastic_co_v1beta1;
#[cfg(feature = "binding_operators_coreos_com_v1alpha1")]
pub mod binding_operators_coreos_com_v1alpha1;
#[cfg(feature = "bitnami_com_v1alpha1")]
pub mod bitnami_com_v1alpha1;
#[cfg(feature = "boskos_k8s_io_v1")]
pub mod boskos_k8s_io_v1;
#[cfg(feature = "bpfd_dev_v1alpha1")]
pub mod bpfd_dev_v1alpha1;
#[cfg(feature = "bus_volcano_sh_v1alpha1")]
pub mod bus_volcano_sh_v1alpha1;
#[cfg(feature = "cache_kubedl_io_v1alpha1")]
pub mod cache_kubedl_io_v1alpha1;
#[cfg(feature = "caching_ibm_com_v1alpha1")]
pub mod caching_ibm_com_v1alpha1;
#[cfg(feature = "camel_apache_org_v1")]
pub mod camel_apache_org_v1;
#[cfg(feature = "camel_apache_org_v1alpha1")]
pub mod camel_apache_org_v1alpha1;
#[cfg(feature = "capsule_clastix_io_v1alpha1")]
pub mod capsule_clastix_io_v1alpha1;
#[cfg(feature = "capsule_clastix_io_v1beta1")]
pub mod capsule_clastix_io_v1beta1;
#[cfg(feature = "capsule_clastix_io_v1beta2")]
pub mod capsule_clastix_io_v1beta2;
#[cfg(feature = "ceph_rook_io_v1")]
pub mod ceph_rook_io_v1;
#[cfg(feature = "cert_manager_io_v1")]
pub mod cert_manager_io_v1;
#[cfg(feature = "chaos_mesh_org_v1alpha1")]
pub mod chaos_mesh_org_v1alpha1;
#[cfg(feature = "che_eclipse_org_v1alpha1")]
pub mod che_eclipse_org_v1alpha1;
#[cfg(feature = "cilium_io_v2")]
pub mod cilium_io_v2;
#[cfg(feature = "cilium_io_v2alpha1")]
pub mod cilium_io_v2alpha1;
#[cfg(feature = "cloudformation_linki_space_v1alpha1")]
pub mod cloudformation_linki_space_v1alpha1;
#[cfg(feature = "cluster_clusterpedia_io_v1alpha2")]
pub mod cluster_clusterpedia_io_v1alpha2;
#[cfg(feature = "cluster_ipfs_io_v1alpha1")]
pub mod cluster_ipfs_io_v1alpha1;
#[cfg(feature = "cluster_x_k8s_io_v1alpha4")]
pub mod cluster_x_k8s_io_v1alpha4;
#[cfg(feature = "cluster_x_k8s_io_v1beta1")]
pub mod cluster_x_k8s_io_v1beta1;
#[cfg(feature = "clusters_clusternet_io_v1beta1")]
pub mod clusters_clusternet_io_v1beta1;
#[cfg(feature = "config_gatekeeper_sh_v1alpha1")]
pub mod config_gatekeeper_sh_v1alpha1;
#[cfg(feature = "config_grafana_com_v1")]
pub mod config_grafana_com_v1;
#[cfg(feature = "config_karmada_io_v1alpha1")]
pub mod config_karmada_io_v1alpha1;
#[cfg(feature = "config_koordinator_sh_v1alpha1")]
pub mod config_koordinator_sh_v1alpha1;
#[cfg(feature = "core_linuxsuren_github_com_v1alpha1")]
pub mod core_linuxsuren_github_com_v1alpha1;
#[cfg(feature = "core_openfeature_dev_v1alpha1")]
pub mod core_openfeature_dev_v1alpha1;
#[cfg(feature = "core_openfeature_dev_v1alpha2")]
pub mod core_openfeature_dev_v1alpha2;
#[cfg(feature = "couchbase_com_v2")]
pub mod couchbase_com_v2;
#[cfg(feature = "crd_projectcalico_org_v1")]
pub mod crd_projectcalico_org_v1;
#[cfg(feature = "data_fluid_io_v1alpha1")]
pub mod data_fluid_io_v1alpha1;
#[cfg(feature = "databases_schemahero_io_v1alpha4")]
pub mod databases_schemahero_io_v1alpha4;
#[cfg(feature = "devices_kubeedge_io_v1alpha2")]
pub mod devices_kubeedge_io_v1alpha2;
#[cfg(feature = "digitalis_io_v1")]
pub mod digitalis_io_v1;
#[cfg(feature = "digitalis_io_v1beta1")]
pub mod digitalis_io_v1beta1;
#[cfg(feature = "druid_apache_org_v1alpha1")]
pub mod druid_apache_org_v1alpha1;
#[cfg(feature = "dynamodb_services_k8s_aws_v1alpha1")]
pub mod dynamodb_services_k8s_aws_v1alpha1;
#[cfg(feature = "ec2_services_k8s_aws_v1alpha1")]
pub mod ec2_services_k8s_aws_v1alpha1;
#[cfg(feature = "ecr_services_k8s_aws_v1alpha1")]
pub mod ecr_services_k8s_aws_v1alpha1;
#[cfg(feature = "eks_services_k8s_aws_v1alpha1")]
pub mod eks_services_k8s_aws_v1alpha1;
#[cfg(feature = "elasticache_services_k8s_aws_v1alpha1")]
pub mod elasticache_services_k8s_aws_v1alpha1;
#[cfg(feature = "elasticsearch_k8s_elastic_co_v1")]
pub mod elasticsearch_k8s_elastic_co_v1;
#[cfg(feature = "elasticsearch_k8s_elastic_co_v1beta1")]
pub mod elasticsearch_k8s_elastic_co_v1beta1;
#[cfg(feature = "elbv2_k8s_aws_v1alpha1")]
pub mod elbv2_k8s_aws_v1alpha1;
#[cfg(feature = "elbv2_k8s_aws_v1beta1")]
pub mod elbv2_k8s_aws_v1beta1;
#[cfg(feature = "emrcontainers_services_k8s_aws_v1alpha1")]
pub mod emrcontainers_services_k8s_aws_v1alpha1;
#[cfg(feature = "enterprisesearch_k8s_elastic_co_v1")]
pub mod enterprisesearch_k8s_elastic_co_v1;
#[cfg(feature = "enterprisesearch_k8s_elastic_co_v1beta1")]
pub mod enterprisesearch_k8s_elastic_co_v1beta1;
#[cfg(feature = "execution_furiko_io_v1alpha1")]
pub mod execution_furiko_io_v1alpha1;
#[cfg(feature = "executor_testkube_io_v1")]
pub mod executor_testkube_io_v1;
#[cfg(feature = "expansion_gatekeeper_sh_v1alpha1")]
pub mod expansion_gatekeeper_sh_v1alpha1;
#[cfg(feature = "expansion_gatekeeper_sh_v1beta1")]
pub mod expansion_gatekeeper_sh_v1beta1;
#[cfg(feature = "external_secrets_io_v1alpha1")]
pub mod external_secrets_io_v1alpha1;
#[cfg(feature = "external_secrets_io_v1beta1")]
pub mod external_secrets_io_v1beta1;
#[cfg(feature = "externaldata_gatekeeper_sh_v1alpha1")]
pub mod externaldata_gatekeeper_sh_v1alpha1;
#[cfg(feature = "externaldata_gatekeeper_sh_v1beta1")]
pub mod externaldata_gatekeeper_sh_v1beta1;
#[cfg(feature = "externaldns_k8s_io_v1alpha1")]
pub mod externaldns_k8s_io_v1alpha1;
#[cfg(feature = "externaldns_nginx_org_v1")]
pub mod externaldns_nginx_org_v1;
#[cfg(feature = "flagger_app_v1beta1")]
pub mod flagger_app_v1beta1;
#[cfg(feature = "flink_apache_org_v1beta1")]
pub mod flink_apache_org_v1beta1;
#[cfg(feature = "flow_volcano_sh_v1alpha1")]
pub mod flow_volcano_sh_v1alpha1;
#[cfg(feature = "flows_netobserv_io_v1alpha1")]
pub mod flows_netobserv_io_v1alpha1;
#[cfg(feature = "flows_netobserv_io_v1beta1")]
pub mod flows_netobserv_io_v1beta1;
#[cfg(feature = "flows_netobserv_io_v1beta2")]
pub mod flows_netobserv_io_v1beta2;
#[cfg(feature = "flux_framework_org_v1alpha1")]
pub mod flux_framework_org_v1alpha1;
#[cfg(feature = "gateway_networking_k8s_io_v1")]
pub mod gateway_networking_k8s_io_v1;
#[cfg(feature = "gateway_networking_k8s_io_v1alpha2")]
pub mod gateway_networking_k8s_io_v1alpha2;
#[cfg(feature = "gateway_networking_k8s_io_v1beta1")]
pub mod gateway_networking_k8s_io_v1beta1;
#[cfg(feature = "gateway_nginx_org_v1alpha1")]
pub mod gateway_nginx_org_v1alpha1;
#[cfg(feature = "getambassador_io_v3alpha1")]
pub mod getambassador_io_v3alpha1;
#[cfg(feature = "grafana_integreatly_org_v1beta1")]
pub mod grafana_integreatly_org_v1beta1;
#[cfg(feature = "hazelcast_com_v1alpha1")]
pub mod hazelcast_com_v1alpha1;
#[cfg(feature = "helm_toolkit_fluxcd_io_v2beta1")]
pub mod helm_toolkit_fluxcd_io_v2beta1;
#[cfg(feature = "hive_openshift_io_v1")]
pub mod hive_openshift_io_v1;
#[cfg(feature = "hiveinternal_openshift_io_v1alpha1")]
pub mod hiveinternal_openshift_io_v1alpha1;
#[cfg(feature = "hnc_x_k8s_io_v1alpha2")]
pub mod hnc_x_k8s_io_v1alpha2;
#[cfg(feature = "hyperfoil_io_v1alpha1")]
pub mod hyperfoil_io_v1alpha1;
#[cfg(feature = "hyperfoil_io_v1alpha2")]
pub mod hyperfoil_io_v1alpha2;
#[cfg(feature = "iam_services_k8s_aws_v1alpha1")]
pub mod iam_services_k8s_aws_v1alpha1;
#[cfg(feature = "ibmcloud_ibm_com_v1alpha1")]
pub mod ibmcloud_ibm_com_v1alpha1;
#[cfg(feature = "image_toolkit_fluxcd_io_v1beta1")]
pub mod image_toolkit_fluxcd_io_v1beta1;
#[cfg(feature = "image_toolkit_fluxcd_io_v1beta2")]
pub mod image_toolkit_fluxcd_io_v1beta2;
#[cfg(feature = "imaging_ingestion_alvearie_org_v1alpha1")]
pub mod imaging_ingestion_alvearie_org_v1alpha1;
#[cfg(feature = "inference_kubedl_io_v1alpha1")]
pub mod inference_kubedl_io_v1alpha1;
#[cfg(feature = "infinispan_org_v2alpha1")]
pub mod infinispan_org_v2alpha1;
#[cfg(feature = "infrastructure_cluster_x_k8s_io_v1alpha1")]
pub mod infrastructure_cluster_x_k8s_io_v1alpha1;
#[cfg(feature = "infrastructure_cluster_x_k8s_io_v1beta1")]
pub mod infrastructure_cluster_x_k8s_io_v1beta1;
#[cfg(feature = "infrastructure_cluster_x_k8s_io_v1beta2")]
pub mod infrastructure_cluster_x_k8s_io_v1beta2;
#[cfg(feature = "installation_mattermost_com_v1beta1")]
pub mod installation_mattermost_com_v1beta1;
#[cfg(feature = "iot_eclipse_org_v1alpha1")]
pub mod iot_eclipse_org_v1alpha1;
#[cfg(feature = "ipam_cluster_x_k8s_io_v1alpha1")]
pub mod ipam_cluster_x_k8s_io_v1alpha1;
#[cfg(feature = "ipam_cluster_x_k8s_io_v1beta1")]
pub mod ipam_cluster_x_k8s_io_v1beta1;
#[cfg(feature = "jaegertracing_io_v1")]
pub mod jaegertracing_io_v1;
#[cfg(feature = "jobset_x_k8s_io_v1alpha2")]
pub mod jobset_x_k8s_io_v1alpha2;
#[cfg(feature = "k8gb_absa_oss_v1beta1")]
pub mod k8gb_absa_oss_v1beta1;
#[cfg(feature = "k8s_nginx_org_v1")]
pub mod k8s_nginx_org_v1;
#[cfg(feature = "k8s_nginx_org_v1alpha1")]
pub mod k8s_nginx_org_v1alpha1;
#[cfg(feature = "k8s_otterize_com_v1alpha2")]
pub mod k8s_otterize_com_v1alpha2;
#[cfg(feature = "k8s_otterize_com_v1alpha3")]
pub mod k8s_otterize_com_v1alpha3;
#[cfg(feature = "kafka_strimzi_io_v1alpha1")]
pub mod kafka_strimzi_io_v1alpha1;
#[cfg(feature = "kafka_strimzi_io_v1beta1")]
pub mod kafka_strimzi_io_v1beta1;
#[cfg(feature = "kafka_strimzi_io_v1beta2")]
pub mod kafka_strimzi_io_v1beta2;
#[cfg(feature = "keda_sh_v1alpha1")]
pub mod keda_sh_v1alpha1;
#[cfg(feature = "keycloak_org_v1alpha1")]
pub mod keycloak_org_v1alpha1;
#[cfg(feature = "kibana_k8s_elastic_co_v1")]
pub mod kibana_k8s_elastic_co_v1;
#[cfg(feature = "kibana_k8s_elastic_co_v1beta1")]
pub mod kibana_k8s_elastic_co_v1beta1;
#[cfg(feature = "kms_services_k8s_aws_v1alpha1")]
pub mod kms_services_k8s_aws_v1alpha1;
#[cfg(feature = "kubean_io_v1alpha1")]
pub mod kubean_io_v1alpha1;
#[cfg(feature = "kubevious_io_v1alpha1")]
pub mod kubevious_io_v1alpha1;
#[cfg(feature = "kueue_x_k8s_io_v1beta1")]
pub mod kueue_x_k8s_io_v1beta1;
#[cfg(feature = "kuma_io_v1alpha1")]
pub mod kuma_io_v1alpha1;
#[cfg(feature = "kustomize_toolkit_fluxcd_io_v1")]
pub mod kustomize_toolkit_fluxcd_io_v1;
#[cfg(feature = "kustomize_toolkit_fluxcd_io_v1beta1")]
pub mod kustomize_toolkit_fluxcd_io_v1beta1;
#[cfg(feature = "kustomize_toolkit_fluxcd_io_v1beta2")]
pub mod kustomize_toolkit_fluxcd_io_v1beta2;
#[cfg(feature = "kyverno_io_v1")]
pub mod kyverno_io_v1;
#[cfg(feature = "kyverno_io_v1alpha2")]
pub mod kyverno_io_v1alpha2;
#[cfg(feature = "kyverno_io_v1beta1")]
pub mod kyverno_io_v1beta1;
#[cfg(feature = "kyverno_io_v2alpha1")]
pub mod kyverno_io_v2alpha1;
#[cfg(feature = "kyverno_io_v2beta1")]
pub mod kyverno_io_v2beta1;
#[cfg(feature = "lambda_services_k8s_aws_v1alpha1")]
pub mod lambda_services_k8s_aws_v1alpha1;
#[cfg(feature = "lerentis_uploadfilter24_eu_v1beta4")]
pub mod lerentis_uploadfilter24_eu_v1beta4;
#[cfg(feature = "litmuschaos_io_v1alpha1")]
pub mod litmuschaos_io_v1alpha1;
#[cfg(feature = "logging_banzaicloud_io_v1alpha1")]
pub mod logging_banzaicloud_io_v1alpha1;
#[cfg(feature = "logging_banzaicloud_io_v1beta1")]
pub mod logging_banzaicloud_io_v1beta1;
#[cfg(feature = "logging_extensions_banzaicloud_io_v1alpha1")]
pub mod logging_extensions_banzaicloud_io_v1alpha1;
#[cfg(feature = "loki_grafana_com_v1")]
pub mod loki_grafana_com_v1;
#[cfg(feature = "loki_grafana_com_v1beta1")]
pub mod loki_grafana_com_v1beta1;
#[cfg(feature = "longhorn_io_v1beta2")]
pub mod longhorn_io_v1beta2;
#[cfg(feature = "maps_k8s_elastic_co_v1alpha1")]
pub mod maps_k8s_elastic_co_v1alpha1;
#[cfg(feature = "mariadb_mmontes_io_v1alpha1")]
pub mod mariadb_mmontes_io_v1alpha1;
#[cfg(feature = "mattermost_com_v1alpha1")]
pub mod mattermost_com_v1alpha1;
#[cfg(feature = "metacontroller_k8s_io_v1alpha1")]
pub mod metacontroller_k8s_io_v1alpha1;
#[cfg(feature = "metal3_io_v1alpha1")]
pub mod metal3_io_v1alpha1;
#[cfg(feature = "minio_min_io_v2")]
pub mod minio_min_io_v2;
#[cfg(feature = "mirrors_kts_studio_v1alpha1")]
pub mod mirrors_kts_studio_v1alpha1;
#[cfg(feature = "mirrors_kts_studio_v1alpha2")]
pub mod mirrors_kts_studio_v1alpha2;
#[cfg(feature = "model_kubedl_io_v1alpha1")]
pub mod model_kubedl_io_v1alpha1;
#[cfg(feature = "monitoring_coreos_com_v1")]
pub mod monitoring_coreos_com_v1;
#[cfg(feature = "monitoring_coreos_com_v1alpha1")]
pub mod monitoring_coreos_com_v1alpha1;
#[cfg(feature = "monitoring_coreos_com_v1beta1")]
pub mod monitoring_coreos_com_v1beta1;
#[cfg(feature = "monocle_monocle_change_metrics_io_v1alpha1")]
pub mod monocle_monocle_change_metrics_io_v1alpha1;
#[cfg(feature = "mq_services_k8s_aws_v1alpha1")]
pub mod mq_services_k8s_aws_v1alpha1;
#[cfg(feature = "multicluster_x_k8s_io_v1alpha1")]
pub mod multicluster_x_k8s_io_v1alpha1;
#[cfg(feature = "mutations_gatekeeper_sh_v1")]
pub mod mutations_gatekeeper_sh_v1;
#[cfg(feature = "mutations_gatekeeper_sh_v1alpha1")]
pub mod mutations_gatekeeper_sh_v1alpha1;
#[cfg(feature = "mutations_gatekeeper_sh_v1beta1")]
pub mod mutations_gatekeeper_sh_v1beta1;
#[cfg(feature = "networking_karmada_io_v1alpha1")]
pub mod networking_karmada_io_v1alpha1;
#[cfg(feature = "nfd_k8s_sigs_io_v1alpha1")]
pub mod nfd_k8s_sigs_io_v1alpha1;
#[cfg(feature = "nfd_kubernetes_io_v1")]
pub mod nfd_kubernetes_io_v1;
#[cfg(feature = "nfd_kubernetes_io_v1alpha1")]
pub mod nfd_kubernetes_io_v1alpha1;
#[cfg(feature = "nodeinfo_volcano_sh_v1alpha1")]
pub mod nodeinfo_volcano_sh_v1alpha1;
#[cfg(feature = "notebook_kubedl_io_v1alpha1")]
pub mod notebook_kubedl_io_v1alpha1;
#[cfg(feature = "notification_toolkit_fluxcd_io_v1")]
pub mod notification_toolkit_fluxcd_io_v1;
#[cfg(feature = "notification_toolkit_fluxcd_io_v1beta1")]
pub mod notification_toolkit_fluxcd_io_v1beta1;
#[cfg(feature = "notification_toolkit_fluxcd_io_v1beta2")]
pub mod notification_toolkit_fluxcd_io_v1beta2;
#[cfg(feature = "opensearchservice_services_k8s_aws_v1alpha1")]
pub mod opensearchservice_services_k8s_aws_v1alpha1;
#[cfg(feature = "opentelemetry_io_v1alpha1")]
pub mod opentelemetry_io_v1alpha1;
#[cfg(feature = "operations_kubeedge_io_v1alpha1")]
pub mod operations_kubeedge_io_v1alpha1;
#[cfg(feature = "operator_aquasec_com_v1alpha1")]
pub mod operator_aquasec_com_v1alpha1;
#[cfg(feature = "operator_cluster_x_k8s_io_v1alpha1")]
pub mod operator_cluster_x_k8s_io_v1alpha1;
#[cfg(feature = "operator_cluster_x_k8s_io_v1alpha2")]
pub mod operator_cluster_x_k8s_io_v1alpha2;
#[cfg(feature = "operator_cryostat_io_v1beta1")]
pub mod operator_cryostat_io_v1beta1;
#[cfg(feature = "operator_open_cluster_management_io_v1")]
pub mod operator_open_cluster_management_io_v1;
#[cfg(feature = "operator_shipwright_io_v1alpha1")]
pub mod operator_shipwright_io_v1alpha1;
#[cfg(feature = "operator_tigera_io_v1")]
pub mod operator_tigera_io_v1;
#[cfg(feature = "operator_victoriametrics_com_v1beta1")]
pub mod operator_victoriametrics_com_v1beta1;
#[cfg(feature = "org_eclipse_che_v1")]
pub mod org_eclipse_che_v1;
#[cfg(feature = "org_eclipse_che_v2")]
pub mod org_eclipse_che_v2;
#[cfg(feature = "pkg_crossplane_io_v1")]
pub mod pkg_crossplane_io_v1;
#[cfg(feature = "pkg_crossplane_io_v1alpha1")]
pub mod pkg_crossplane_io_v1alpha1;
#[cfg(feature = "pkg_crossplane_io_v1beta1")]
pub mod pkg_crossplane_io_v1beta1;
#[cfg(feature = "policy_clusterpedia_io_v1alpha1")]
pub mod policy_clusterpedia_io_v1alpha1;
#[cfg(feature = "policy_karmada_io_v1alpha1")]
pub mod policy_karmada_io_v1alpha1;
#[cfg(feature = "postgres_operator_crunchydata_com_v1beta1")]
pub mod postgres_operator_crunchydata_com_v1beta1;
#[cfg(feature = "postgresql_cnpg_io_v1")]
pub mod postgresql_cnpg_io_v1;
#[cfg(feature = "prometheusservice_services_k8s_aws_v1alpha1")]
pub mod prometheusservice_services_k8s_aws_v1alpha1;
#[cfg(feature = "quay_redhat_com_v1")]
pub mod quay_redhat_com_v1;
#[cfg(feature = "ray_io_v1")]
pub mod ray_io_v1;
#[cfg(feature = "ray_io_v1alpha1")]
pub mod ray_io_v1alpha1;
#[cfg(feature = "rds_services_k8s_aws_v1alpha1")]
pub mod rds_services_k8s_aws_v1alpha1;
#[cfg(feature = "redhatcop_redhat_io_v1alpha1")]
pub mod redhatcop_redhat_io_v1alpha1;
#[cfg(feature = "registry_apicur_io_v1")]
pub mod registry_apicur_io_v1;
#[cfg(feature = "registry_devfile_io_v1alpha1")]
pub mod registry_devfile_io_v1alpha1;
#[cfg(feature = "reliablesyncs_kubeedge_io_v1alpha1")]
pub mod reliablesyncs_kubeedge_io_v1alpha1;
#[cfg(feature = "repo_manager_pulpproject_org_v1beta2")]
pub mod repo_manager_pulpproject_org_v1beta2;
#[cfg(feature = "resources_teleport_dev_v1")]
pub mod resources_teleport_dev_v1;
#[cfg(feature = "resources_teleport_dev_v2")]
pub mod resources_teleport_dev_v2;
#[cfg(feature = "resources_teleport_dev_v3")]
pub mod resources_teleport_dev_v3;
#[cfg(feature = "rocketmq_apache_org_v1alpha1")]
pub mod rocketmq_apache_org_v1alpha1;
#[cfg(feature = "rules_kubeedge_io_v1")]
pub mod rules_kubeedge_io_v1;
#[cfg(feature = "runtime_cluster_x_k8s_io_v1alpha1")]
pub mod runtime_cluster_x_k8s_io_v1alpha1;
#[cfg(feature = "s3_services_k8s_aws_v1alpha1")]
pub mod s3_services_k8s_aws_v1alpha1;
#[cfg(feature = "sagemaker_services_k8s_aws_v1alpha1")]
pub mod sagemaker_services_k8s_aws_v1alpha1;
#[cfg(feature = "scheduling_koordinator_sh_v1alpha1")]
pub mod scheduling_koordinator_sh_v1alpha1;
#[cfg(feature = "scheduling_sigs_k8s_io_v1alpha1")]
pub mod scheduling_sigs_k8s_io_v1alpha1;
#[cfg(feature = "scheduling_volcano_sh_v1beta1")]
pub mod scheduling_volcano_sh_v1beta1;
#[cfg(feature = "schemas_schemahero_io_v1alpha4")]
pub mod schemas_schemahero_io_v1alpha4;
#[cfg(feature = "scylla_scylladb_com_v1")]
pub mod scylla_scylladb_com_v1;
#[cfg(feature = "scylla_scylladb_com_v1alpha1")]
pub mod scylla_scylladb_com_v1alpha1;
#[cfg(feature = "secretgenerator_mittwald_de_v1alpha1")]
pub mod secretgenerator_mittwald_de_v1alpha1;
#[cfg(feature = "secrets_crossplane_io_v1alpha1")]
pub mod secrets_crossplane_io_v1alpha1;
#[cfg(feature = "secscan_quay_redhat_com_v1alpha1")]
pub mod secscan_quay_redhat_com_v1alpha1;
#[cfg(feature = "security_profiles_operator_x_k8s_io_v1alpha1")]
pub mod security_profiles_operator_x_k8s_io_v1alpha1;
#[cfg(feature = "security_profiles_operator_x_k8s_io_v1alpha2")]
pub mod security_profiles_operator_x_k8s_io_v1alpha2;
#[cfg(feature = "security_profiles_operator_x_k8s_io_v1beta1")]
pub mod security_profiles_operator_x_k8s_io_v1beta1;
#[cfg(feature = "servicebinding_io_v1alpha3")]
pub mod servicebinding_io_v1alpha3;
#[cfg(feature = "servicebinding_io_v1beta1")]
pub mod servicebinding_io_v1beta1;
#[cfg(feature = "services_k8s_aws_v1alpha1")]
pub mod services_k8s_aws_v1alpha1;
#[cfg(feature = "serving_kubedl_io_v1alpha1")]
pub mod serving_kubedl_io_v1alpha1;
#[cfg(feature = "sfn_services_k8s_aws_v1alpha1")]
pub mod sfn_services_k8s_aws_v1alpha1;
#[cfg(feature = "site_superedge_io_v1alpha1")]
pub mod site_superedge_io_v1alpha1;
#[cfg(feature = "slo_koordinator_sh_v1alpha1")]
pub mod slo_koordinator_sh_v1alpha1;
#[cfg(feature = "source_toolkit_fluxcd_io_v1beta1")]
pub mod source_toolkit_fluxcd_io_v1beta1;
#[cfg(feature = "source_toolkit_fluxcd_io_v1beta2")]
pub mod source_toolkit_fluxcd_io_v1beta2;
#[cfg(feature = "sparkoperator_k8s_io_v1beta2")]
pub mod sparkoperator_k8s_io_v1beta2;
#[cfg(feature = "status_gatekeeper_sh_v1beta1")]
pub mod status_gatekeeper_sh_v1beta1;
#[cfg(feature = "stunner_l7mp_io_v1alpha1")]
pub mod stunner_l7mp_io_v1alpha1;
#[cfg(feature = "templates_gatekeeper_sh_v1")]
pub mod templates_gatekeeper_sh_v1;
#[cfg(feature = "templates_gatekeeper_sh_v1alpha1")]
pub mod templates_gatekeeper_sh_v1alpha1;
#[cfg(feature = "templates_gatekeeper_sh_v1beta1")]
pub mod templates_gatekeeper_sh_v1beta1;
#[cfg(feature = "tests_testkube_io_v1")]
pub mod tests_testkube_io_v1;
#[cfg(feature = "tests_testkube_io_v2")]
pub mod tests_testkube_io_v2;
#[cfg(feature = "tests_testkube_io_v3")]
pub mod tests_testkube_io_v3;
#[cfg(feature = "topology_node_k8s_io_v1alpha1")]
pub mod topology_node_k8s_io_v1alpha1;
#[cfg(feature = "traefik_io_v1alpha1")]
pub mod traefik_io_v1alpha1;
#[cfg(feature = "training_kubedl_io_v1alpha1")]
pub mod training_kubedl_io_v1alpha1;
#[cfg(feature = "virt_virtink_smartx_com_v1alpha1")]
pub mod virt_virtink_smartx_com_v1alpha1;
#[cfg(feature = "wgpolicyk8s_io_v1alpha1")]
pub mod wgpolicyk8s_io_v1alpha1;
#[cfg(feature = "wgpolicyk8s_io_v1alpha2")]
pub mod wgpolicyk8s_io_v1alpha2;
#[cfg(feature = "wgpolicyk8s_io_v1beta1")]
pub mod wgpolicyk8s_io_v1beta1;
#[cfg(feature = "wildfly_org_v1alpha1")]
pub mod wildfly_org_v1alpha1;
#[cfg(feature = "work_karmada_io_v1alpha1")]
pub mod work_karmada_io_v1alpha1;
#[cfg(feature = "work_karmada_io_v1alpha2")]
pub mod work_karmada_io_v1alpha2;
