apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "workloadprofiles.kubevious.io"
spec:
  group: "kubevious.io"
  names:
    kind: "WorkloadProfile"
    listKind: "WorkloadProfileList"
    plural: "workloadprofiles"
    shortNames:
      - "workpr"
    singular: "workloadprofile"
  scope: "Namespaced"
  versions:
    - name: "v1alpha1"
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                affinity:
                  properties:
                    nodeAffinity:
                      properties:
                        preferredDuringSchedulingIgnoredDuringExecution:
                          items:
                            properties:
                              preference:
                                properties:
                                  matchExpressions:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                  matchFields:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                type: "object"
                              weight:
                                format: "int32"
                                type: "integer"
                            required:
                              - "preference"
                              - "weight"
                            type: "object"
                          type: "array"
                        requiredDuringSchedulingIgnoredDuringExecution:
                          properties:
                            nodeSelectorTerms:
                              items:
                                properties:
                                  matchExpressions:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                  matchFields:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                type: "object"
                              type: "array"
                          required:
                            - "nodeSelectorTerms"
                          type: "object"
                      type: "object"
                    podAffinity:
                      properties:
                        preferredDuringSchedulingIgnoredDuringExecution:
                          items:
                            properties:
                              podAffinityTerm:
                                properties:
                                  labelSelector:
                                    properties:
                                      matchExpressions:
                                        items:
                                          properties:
                                            key:
                                              type: "string"
                                            operator:
                                              type: "string"
                                            values:
                                              items:
                                                type: "string"
                                              type: "array"
                                          required:
                                            - "key"
                                            - "operator"
                                          type: "object"
                                        type: "array"
                                      matchLabels:
                                        additionalProperties:
                                          type: "string"
                                        type: "object"
                                    type: "object"
                                  namespaceSelector:
                                    properties:
                                      matchExpressions:
                                        items:
                                          properties:
                                            key:
                                              type: "string"
                                            operator:
                                              type: "string"
                                            values:
                                              items:
                                                type: "string"
                                              type: "array"
                                          required:
                                            - "key"
                                            - "operator"
                                          type: "object"
                                        type: "array"
                                      matchLabels:
                                        additionalProperties:
                                          type: "string"
                                        type: "object"
                                    type: "object"
                                  namespaces:
                                    items:
                                      type: "string"
                                    type: "array"
                                  topologyKey:
                                    type: "string"
                                required:
                                  - "topologyKey"
                                type: "object"
                              weight:
                                format: "int32"
                                type: "integer"
                            required:
                              - "podAffinityTerm"
                              - "weight"
                            type: "object"
                          type: "array"
                        requiredDuringSchedulingIgnoredDuringExecution:
                          items:
                            properties:
                              labelSelector:
                                properties:
                                  matchExpressions:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                  matchLabels:
                                    additionalProperties:
                                      type: "string"
                                    type: "object"
                                type: "object"
                              namespaceSelector:
                                properties:
                                  matchExpressions:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                  matchLabels:
                                    additionalProperties:
                                      type: "string"
                                    type: "object"
                                type: "object"
                              namespaces:
                                items:
                                  type: "string"
                                type: "array"
                              topologyKey:
                                type: "string"
                            required:
                              - "topologyKey"
                            type: "object"
                          type: "array"
                      type: "object"
                    podAntiAffinity:
                      properties:
                        preferredDuringSchedulingIgnoredDuringExecution:
                          items:
                            properties:
                              podAffinityTerm:
                                properties:
                                  labelSelector:
                                    properties:
                                      matchExpressions:
                                        items:
                                          properties:
                                            key:
                                              type: "string"
                                            operator:
                                              type: "string"
                                            values:
                                              items:
                                                type: "string"
                                              type: "array"
                                          required:
                                            - "key"
                                            - "operator"
                                          type: "object"
                                        type: "array"
                                      matchLabels:
                                        additionalProperties:
                                          type: "string"
                                        type: "object"
                                    type: "object"
                                  namespaceSelector:
                                    properties:
                                      matchExpressions:
                                        items:
                                          properties:
                                            key:
                                              type: "string"
                                            operator:
                                              type: "string"
                                            values:
                                              items:
                                                type: "string"
                                              type: "array"
                                          required:
                                            - "key"
                                            - "operator"
                                          type: "object"
                                        type: "array"
                                      matchLabels:
                                        additionalProperties:
                                          type: "string"
                                        type: "object"
                                    type: "object"
                                  namespaces:
                                    items:
                                      type: "string"
                                    type: "array"
                                  topologyKey:
                                    type: "string"
                                required:
                                  - "topologyKey"
                                type: "object"
                              weight:
                                format: "int32"
                                type: "integer"
                            required:
                              - "podAffinityTerm"
                              - "weight"
                            type: "object"
                          type: "array"
                        requiredDuringSchedulingIgnoredDuringExecution:
                          items:
                            properties:
                              labelSelector:
                                properties:
                                  matchExpressions:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                  matchLabels:
                                    additionalProperties:
                                      type: "string"
                                    type: "object"
                                type: "object"
                              namespaceSelector:
                                properties:
                                  matchExpressions:
                                    items:
                                      properties:
                                        key:
                                          type: "string"
                                        operator:
                                          type: "string"
                                        values:
                                          items:
                                            type: "string"
                                          type: "array"
                                      required:
                                        - "key"
                                        - "operator"
                                      type: "object"
                                    type: "array"
                                  matchLabels:
                                    additionalProperties:
                                      type: "string"
                                    type: "object"
                                type: "object"
                              namespaces:
                                items:
                                  type: "string"
                                type: "array"
                              topologyKey:
                                type: "string"
                            required:
                              - "topologyKey"
                            type: "object"
                          type: "array"
                      type: "object"
                  type: "object"
                annotations:
                  additionalProperties:
                    type: "string"
                  type: "object"
                infra:
                  default: "k8s"
                  enum:
                    - "k8s"
                    - "serverless"
                  type: "string"
                labels:
                  additionalProperties:
                    type: "string"
                  type: "object"
                nodeSelector:
                  additionalProperties:
                    type: "string"
                  type: "object"
                  x-kubernetes-map-type: "atomic"
                replicas:
                  pattern: "^[0-9]+%$"
                  x-kubernetes-int-or-string: true
              type: "object"
          required:
            - "spec"
          type: "object"
      served: true
      storage: true
