# SPDX-FileCopyrightText: The kube-custom-resources-rs Authors
# SPDX-License-Identifier: 0BSD

name: Update CRDs
on:
  schedule:
    - cron: 53 15 * * FRI
  workflow_dispatch:
jobs:
  update:
    name: Update CRDs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install kopium
        run: cargo install kopium
      - name: Verify kopium
        run: kopium --version
      - name: Fetch CRDs
        run: cargo run --package code-generator --bin crd_v1_fetcher
      - name: Update dep5
        run: cargo run --package code-generator --bin dep5_generator
      - name: Fixup YAML
        run: find ./crd-catalog -name 'fixup.sh' -type f -exec {} \;
      - name: Generate Resources
        run: ./code-generator/generate.sh
      - name: Generate lib.rs
        run: cargo run --package code-generator --bin lib_rs_generator
      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update upstream specifications to their latest version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update upstream specifications to their latest version
          labels: enhancement
          assignees: sebhoss
          draft: false
          base: main
          branch: update-specs
          delete-branch: true
      - id: automerge
        name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
